name: Build
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.2
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test